use crate::{
    property::PropertyMetadata,
    type_system::{
        OwnedDataType, Reference, TypeRef,
        data_types::{DataTypeKind, TypeDescriptor, Vec3},
    },
};
mod nodes_enum;

mod control_flow;
mod modifiers;
mod producers;
mod transformers;

pub use control_flow::*;
pub use modifiers::*;
pub use nodes_enum::Nodes;
pub use producers::*;
pub use transformers::*;

#[derive(Debug)]
pub enum SetPropertyError {
    NotFound,
    WrongType,
    WrongValue,
    WrongIndex,
}

#[derive(Debug)]
pub struct PropertyNotFound;
pub trait PropertyInterface {
    /// Should be called one time at the start.
    /// Returns the properties in the right order
    /// so they can be queried by Vec index.
    /// Could investigate after const traits or something
    fn get_properties(&self) -> Box<[PropertyMetadata]>;
    //fn try_set_property_unchecked(&mut self,index:u8, value: DataTypeValue)
    fn try_set_property(
        &mut self,
        property_name: &str,
        value: OwnedDataType,
    ) -> Result<(), SetPropertyError>;
    fn try_get_property(&self, property: &str) -> Result<TypeRef, PropertyNotFound>;

    fn try_set_property_index(
        &mut self,
        index: u8,
        value: OwnedDataType,
    ) -> Result<(), SetPropertyError>;
    fn try_get_property_index(&self, index: u8) -> Result<TypeRef, PropertyNotFound>;
    //TODO this could somehow work maybe
    // fn try_get_property_ref<T: DataType>(&self, index: u8) -> Result<&T, PropertyNotFound>;

    //fn try_get_property_script(&self, property: &str) -> Result<String, PropertyNotFound>;

    fn set_property_external(
        &mut self,
        index: u8,
        reference: Reference,
    ) -> Result<(), SetPropertyError>;

    //TODO this is rather bad so idk if it is necessary yet
    fn try_get_property_metadata(&self, index: u8) -> PropertyMetadata {
        self.get_properties()[index as usize].clone()
    }
}

//
#[derive(Clone, Debug)]
pub struct SocketMetadata {
    //MAYBE UNIFY THESE
    pub type_descriptor: TypeDescriptor,
    pub name: Option<String>,
    pub color: Vec3,
    //TODO figure out a doc system
    pub documentation: Option<String>,
}

impl SocketMetadata {
    pub fn get_type(&self) -> DataTypeKind {
        self.type_descriptor.get_type()
    }
    pub fn get_color(&self) -> Vec3 {
        self.color
    }
}

/* impl SocketMetadata {
    pub(crate) fn new(r#type: DataTypeType) -> Self {
        Self {
            type_descriptor: TypeDescriptor {
                r#type,
                mutable: true,
            },
            name: None,
            documentation: None,
        }
    }
} */

pub trait SocketInterface {
    /* fn get_sockets(&self) -> (Vec<DataTypeType>, Vec<DataTypeType>) {
        (self.get_input_sockets(), self.get_output_sockets())
    } */
    fn get_input_sockets(&self) -> Box<[TypeDescriptor]>;
    fn get_output_sockets(&self) -> Box<[TypeDescriptor]>;
}

pub trait Node: PropertyInterface + SocketInterface {
    //fn initialize(&self) ->

    //This could maybe also just take a cloned DataTypeValue instead of references which could
    // be more efficient since it only is 16bytes so idk if pointer chasing is worth.
    // would need to benchmarkwith a rather complex graph.
    //Can also guard this for free with a option but idk if its worth
    //only relevant for the producers
    //fn compute(&self, input_sockets: Option<Box<[DataTypeRef]>>) -> Vec<DataTypeValue>;
    fn compute(
        &self,
        input_sockets: Option<&[Reference]>,
        context: &impl ContextProvider,
        //TODO explore this
        //write_back: Box<[&mut DataTypeValue]>,
    ) -> Box<[Option<OwnedDataType>]>;

    /* //These 4 methods can be generated by a proc macro with the exception of Handlers aka AssetInstance
    fn try_set_property(
        &mut self,
        property: &str,
        value: DataTypeInstance,
        context: Option<&AssetInstance>,
    ) -> Result<(), ()>;
    fn try_get_property(&self, property: &str) -> Result<DataTypeInstance, ()>;
    fn get_properties(&self) -> Box<[PropertyMetadata]>; */
    //TODO switch to slices or iterators most likely
    /* fn get_sockets(&self) -> (Vec<DataTypeType>, Vec<DataTypeType>) {
        (self.get_input_sockets(), self.get_output_sockets())
    }
    fn get_input_sockets(&self) -> Vec<DataTypeType>;
    fn get_output_sockets(&self) -> Vec<DataTypeType>; */

    //#[cfg(not(feature = "only_runtime"))]
    //TODO proper error handling and all cases
    /* fn verify_sockets(&self, input_sockets: Vec<&DataTypeInstance>) -> Result<(), ()> {
        for (index, input) in self.get_sockets().0.iter().enumerate() {
            match input {
                DataTypeType::Omni => return Err(()),
                DataTypeType::Mesh => input_sockets[index]
                    .ge::<OneiroiMesh>()
                    .ok_or_else(|| ()),
                DataTypeType::Collection => todo!(),
                DataTypeType::Instance => todo!(),
                DataTypeType::Curve => todo!(),
                DataTypeType::Collider => todo!(),
                DataTypeType::Vec3 => todo!(),
                DataTypeType::Int => todo!(),
                DataTypeType::Float => todo!(),
                DataTypeType::Curve2d => todo!(),
                DataTypeType::Bool => todo!(),
            };
        }
        Ok(())
    } */

    fn node_metadata(&self) -> StaticNodeMetadata;
}

/* trait NodeDebug: Node {
    fn get_input_sockets_metadata(&self) -> Box<[SocketMetadata]>;
    fn get_output_sockets_metadata(&self) -> Box<[SocketMetadata]>;
} */

/* pub trait TestingNodeExt: Node {
    fn compute(
        &self,
        input_sockets: Option<&[Reference]>,
        context: &impl Processor,
        write_back: Box<[&mut DataTypeValue]>,
    ) -> Box<[u8]>;
} */

/* #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct ContextUid(NodeIndex, u8); */
/*
impl ContextUid {
    pub(crate) fn node(&self) -> NodeIndex {
        self.0
    }
    pub(crate) fn socket(&self) -> u8 {
        self.1
    }

    pub(super) fn new(index: NodeIndex, socket: u8) -> Self {
        Self(index, socket)
    }
} */

//Testing the OutputMetadata Workflow but it might be the same as SocketMetadata
pub struct OutputMetadata {
    data_type: DataTypeKind,
    mutable: bool,
    variance: (),
}

/// The Handler should provide the context which nodes receive to interact with.
/// It is responsible to keep already computed things in its cache and delegate recomputations to the right nodes.
/// These should be the only methods exposed to the outside of the crate regarding anything that requires computation.
pub trait ContextProvider {
    /// Upon starting the computation users must call  
    // fn initialize(&self) -> Option<Box<[OutputMetadata]>>;

    //fn compute(&mut self) -> Vec<Reference>;
    fn get_reference(&self, index: Reference) -> TypeRef;

    //fn set_template(&mut self, base: Arc<AssetTemplate>);

    //fn refenrence_changed(&self) -> bool;

    //n try_set_input_socket(&mut self);

    //fn try_set_exposed_property(&mut self);
}

pub struct StaticNodeMetadata {
    pub color: &'static str,
}
